apiVersion: v1
kind: ServiceAccount
metadata:
  name: ignite
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ignite
  namespace: {{ .Release.Namespace }}
  labels:
    app: ignite
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    resourceNames: ["*"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ignite
  namespace: {{ .Release.Namespace }}
  labels:
    app: ignite
subjects:
  - kind: ServiceAccount
    name: ignite
roleRef:
  kind: Role
  name: ignite
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ printf "%s%s" "ignite-" .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ printf "%s%s" "ignite-cluster-role-binding-" .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: ignite
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ printf "%s%s" "ignite-" .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: ignite
  namespace: {{ .Release.Namespace }}
