apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "ignite.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "ignite.name" . }}
    helm.sh/chart: {{ include "ignite.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ include "ignite.fullname" . }}
  serviceName: {{ include "ignite.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ include "ignite.fullname" . }}
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "ignite.fullname" . }}-configmap
            items:
            - key: ignite-config.xml
              path: default-config.xml
{{- if .Values.metrics.enabled }}
        - name: metrics-config
          configMap:
            name: {{ include "ignite.fullname" . }}-metrics
        - name: jmx-exporter
          emptyDir: {}
{{- end }}
      serviceAccountName: ignite 
{{- if .Values.metrics.enabled }}
      initContainers:
        - name: jmx-exporter-init
          image: "{{ .Values.jmx_exporter.image.repository }}:{{ .Values.jmx_exporter.image.tag }}"
          command:
            - sh
            - -c
            - >
              wget -O /jmx/jmx_prometheus_javaagent.jar
              https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/0.20.0/jmx_prometheus_javaagent-0.20.0.jar
          volumeMounts:
            - name: jmx-exporter
              mountPath: /jmx
{{- end }}
      containers:
      - name: ignite
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        resources:
{{ toYaml .Values.resources | indent 10 }}
        env:
        - name: OPTION_LIBS
          value: ignite-kubernetes,ignite-rest-http
        # - name: CONFIG_URI
        #   value: https://raw.githubusercontent.com/apache/ignite/master/modules/kubernetes/config/example-kube-persistence-and-wal.xml
        - name: IGNITE_QUIET
          value: "false"
        - name: JVM_OPTS
          value: >-
            -Djava.net.preferIPv4Stack=true
            {{- if .Values.metrics.enabled }}
            -javaagent:/opt/jmx/jmx_prometheus_javaagent.jar={{ .Values.metrics.service.port }}:/opt/jmx/config/jmx-exporter.yaml
            {{- end }}
        - name: CONFIG_URI
          value: file:///opt/ignite/apache-ignite/config/default-config.xml
        - name: IGNITE_ENABLE_EXPERIMENTAL_COMMAND
          value: "true" 
        ports:
        - containerPort: 11211 # JDBC port number.
        - containerPort: 47100 # communication SPI port number.
        - containerPort: 47500 # discovery SPI port number.
        - containerPort: 49112 # JMX port number.
        - containerPort: 10800 # SQL port number.
        - containerPort: 8080 # REST port number.
        - containerPort: 10900 # Thin clients port number.
{{- if .Values.metrics.enabled }}
        - containerPort: {{ .Values.metrics.service.port }}
          name: metrics
{{- end }}
        volumeMounts:
{{- if (.Values.wal_persistence.enabled) }}
        - mountPath: "/wal"
          name: ignite-wal
{{- end }}
{{- if (.Values.persistence.enabled) }}
        - mountPath: "/persistence"
          name: ignite-persistence
{{- end }}
        - name: config-volume
          mountPath: /opt/ignite/apache-ignite/config
{{- if .Values.metrics.enabled }}
        - name: jmx-exporter
          mountPath: /opt/jmx
        - name: metrics-config
          mountPath: /opt/jmx/config
{{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
  volumeClaimTemplates:
{{- if (.Values.persistence.enabled) }}
  - metadata:
      name: ignite-persistence
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ include "ignite.fullname" . }}-persistence-storage-class-{{ .Release.Namespace }}
      resources:
        requests:
          storage: {{ .Values.persistence.size }}
{{- end }}
{{- if (.Values.wal_persistence.enabled) }}
  - metadata:
      name: ignite-wal
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ include "ignite.fullname" . }}-wal-storage-class-{{ .Release.Namespace }}
      resources:
        requests:
          storage: {{ .Values.wal_persistence.size }}
{{- end }}
