{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ignite.fullname" . }}-metrics
  labels:
    app: {{ include "ignite.fullname" . }}
spec:
  type: {{ .Values.metrics.service.type }}
  ports:
    - name: metrics
      port: {{ .Values.metrics.service.port }}
      targetPort: metrics
      {{- if .Values.metrics.service.nodePort }}
      nodePort: {{ .Values.metrics.service.nodePort }}
      {{- end }}
  selector:
    app: {{ include "ignite.fullname" . }}
{{- end }}
